### ISSUE TITLE
Endpoint for create a category

### ISSUE THREAD

**Issue by nicobytes** [PlatziMaster/fake-store-api#31]
**Is your feature request related to a problem?**
The consumer of the API should be create a new category.

**Describe the solution you'd like**
In the endpoint `[POST] /categories`  should be receive with attrs:

- Name

The expected result:

- Id (auto allocate)
- Name
- Image (auto allocate)

**Comment by betotorodev** [comment]
I'd like to take this issue

**Comment by nicobytes** [comment]
Close for duplicated https://github.com/PlatziMaster/fake-store-api/issues/8
