### ISSUE TITLE
Endpoint to create categories

### ISSUE THREAD

**Issue by nicobytes** [PlatziMaster/fake-store-api#8]
**Is your feature request related to a problem?**
The consumer the API should create a category

**Describe the solution you'd like**
In the endpoint, ` [POST] /categories`:

The Data transfer object:
- Name: string (min: 10, max 120) Only letters and numbers with spaces
- Image: string URL

The backend should generate the ID.

**Comment by eriksape** [comment]
Lo tomo 😄
