### ISSUE TITLE
Search products by name

### ISSUE THREAD

**Issue by nicobytes** [PlatziMaster/fake-store-api#9]
**Is your feature request related to a problem?**
The consumer the API should be filter products by name.

**Describe the solution you'd like**
In the endpoint, `[GET] /products` by Query parameters like this:

| Operator  | Expression |  Example|
| ----------- | ----------- | ----------- |
| Equals/equivalency | attribute=value | /products?query={query}|

Example:

`/products?query=stickers`

**Comment by jinfanv** [comment]
Hi @nicobytes, I would like to work this issues.  You can assign me, please.
